version: "3"
services:
  mongo:
    image: mongo:bionic

  mongodb-bi-connector:
    image: ryanhs/mongodb-bi-connector:latest
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017  
    ports:
      - "3307:3307"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081